branches:
  except:
  - "/^wip/"
  - "/^dependabot/"
language: node_js
sudo: true
dist: xenial
git:
  depth: false
addons:
  mariadb: '10.2'
  firefox: latest-esr
node_js: '12'
cache:
  timeout: 900
  npm: true
  pip: true

stages:
  - test
  - name: deploy
    if: type = push AND branch = master AND repo = stanford-oval/almond-cloud

env:
  global:
  - TZ="America/Los_Angeles"
  - COVERALLS_PARALLEL=true

jobs:
  include:
    -
      name: "Unit Tests"
      install:
      - sudo apt-get update -q -y
      - sudo apt-get install -y realpath
      - travis_retry npm ci
      script:
      - npm run lint
      - ./tests/check-migrations.sh
      - npx nyc ts-node ./tests/unit
      after_success: npm run coverage
    -
      name: "Web Almond Integration Tests"
      install:
      - ./travis/install-webalmond-deps.sh
      - travis_retry npm ci
      - export PATH="`pwd`/geckodriver:$PATH"
      script: npx nyc ./tests/webalmond-integration.sh
      after_success: npm run coverage
    -
      name: "Thingpedia Integration Tests"
      install:
      - ./travis/install-webalmond-deps.sh
      - travis_retry npm ci
      - export PATH="`pwd`/geckodriver:$PATH"
      script: npx nyc ./tests/thingpedia-integration.sh
      after_success: npm run coverage
    -
      name: "NLP Integration Tests"
      install:
      - ./travis/install-webalmond-deps.sh
      - travis_retry npm ci
      - pyenv global 3.7.1
      - ./tests/install-nlp-deps.sh
      - export GENIENLP_EMBEDDINGS=`pwd`/tests/embeddings
      - export PATH="`pwd`/geckodriver:$PATH"
      script: npx nyc ./tests/nlp-integration.sh
      after_success: npm run coverage
    -
      name: "Training Integration Tests"
      install:
      - ./travis/install-webalmond-deps.sh
      - travis_retry npm ci
      - pyenv global 3.7.1
      - ./tests/install-nlp-deps.sh
      - export GENIENLP_EMBEDDINGS=`pwd`/tests/embeddings
      - export PATH="`pwd`/geckodriver:$PATH"
      script: npx nyc ./tests/training-integration.sh
      after_success: npm run coverage
    -
      name: "GO Tests"
      language: go
      install:
      - go get golang.org/x/tools/cmd/cover
      - go get github.com/mattn/goveralls
      go: 1.16.x
      before_script: cd go
      script: go test -v -covermode=count -coverprofile=coverage.out ./...
      after_success: $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -coverprofile=coverage.out -service=travis-ci

notifications:
  webhooks: https://coveralls.io/webhook
  slack:
    secure: fGrI1C4upQI+TvN5AFq5Ncm37tlIEIAq39mZzP259fxxTJZVDrLL9RezzI4o17elCgROnRhOeuK75muAlDWKUK1vvVlG02y6G1qOTfG2paklLpxdGSdJHWyGOoMqv822bSpYpz+Us2hbgIoyRIjzE4QTPtAwUm+aNbQUQX5GLucBrwdkJqTUQVUSEZKjB8i8bl0ORODX2RHLWO1zuLTi/vT39DrFo2fD2yuZHNvgqDZIiIyt+9vPJPF/i1xZdh0/0XZSicAGMBBUS4FuxPWYW0ouR2Joup9jZHMmKZzgTJcPsJKpGU2feeCJebol5SWmgB1nAapfIG1WjSNUtgGKKA4BRpuhq/iZUiBE8dQrcQT2NWBES8MmPkw01xzAAALlsvL2snfVNw37WDCSezv3Ls1aT7ISDFyx29rulan0kqkcWH4e5xFY5g2TZKUPAvNeV6QfhP4RP+L+Eh72Dhk67esVTtdE7S+MX+Czq/nFeMQINPbmf+VzznHJEvEDlGT1qjz+11FxRLgtv+qbEk5UdUs3b56twLQNg3NxCQX53bjI1KRxOmf66+fl4y1DXhH5ka4m9jLoULI2hvpKLyHFg0Cky/ilTrOdfSRtSmaeshnJ3mD58CZry4xscKODwnLFz+yQdu04drto3+5sCNTNZTbxbZPY+an273kUXhXyh4w=
