apiVersion: apps/v1
kind: Deployment
metadata:
  name: "nlp"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "nlp"
  template:
    metadata:
      labels:
        app: "nlp"
    spec:
      containers:
      # main container
      - name: "nlp"
        image: stanfordoval/almond-cloud:latest-decanlp
        imagePullPolicy: Always
        command: ["run-nlp"]
        volumeMounts:
        - name: config
          mountPath: "/etc/almond-cloud"
          readOnly: true
        - name: aws
          mountPath: "/home/almond-cloud/.aws"
          readOnly: true
        resources:
          requests:
            memory: 8G
            ephemeral-storage: 10G
        readinessProbe:
          tcpSocket:
            port: 8400
          initialDelaySeconds: 30
          periodSeconds: 20
      volumes:
      - name: config
        secret:
          secretName: almond-config
      - name: aws
        secret:
          secretName: aws-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "tokenizer"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "tokenizer"
  template:
    metadata:
      labels:
        app: "tokenizer"
    spec:
      containers:
      # main container
      - name: "nlp"
        image: stanfordoval/almond-tokenizer:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: 5G
        readinessProbe:
          tcpSocket:
            port: 8888
          initialDelaySeconds: 10
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: "nlp"
spec:
  ports:
  - port: 8400
    protocol: TCP
  selector:
    app: "nlp"
---
apiVersion: v1
kind: Service
metadata:
  name: "tokenizer"
spec:
  ports:
  - port: 8888
    protocol: TCP
  selector:
    app: "tokenizer"
