apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nlp
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    # set a very large value so we can upload string datasets
    nginx.ingress.kubernetes.io/proxy-body-size: "64m"
  labels:
    app: nlp
spec:
  defaultBackend:
    service:
      name: nlp
      port:
        number: 8400
  rules:
  - host: nlp.almond-cloud.test
    http:
      paths:
      - backend:
          service:
            name: nlp
            port:
              number: 8400
        path: /
        pathType: ImplementationSpecific
